mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('social_django.urls', namespace='social')),
    path("", include('stats.urls', namespace='stats')),
]

stats/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views
app_name='stats'

urlpatterns = [
    path("", views.login, name="login"),
    path("home", views.index, name="index"),
    path("game/<int:appid>", views.game_detail, name="game_detail"),
    path('logout', login_required(views.LogoutView.as_view(), login_url='/login'), name='logout')
]

stats/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _


class SteamUserManager(BaseUserManager):
    def _create_user(self, steamid, password, **extra_fields):
        """
        Creates and saves a User with the given steamid and password.
        """
        try:
            # python social auth provides an empty email param, which cannot be used here
            del extra_fields['email']
        except KeyError:
            pass
        if not steamid:
            raise ValueError('The given steamid must be set')
        user = self.model(steamid=steamid, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, steamid, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(steamid, password, **extra_fields)

    def create_superuser(self, steamid, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(steamid, password, **extra_fields)


class SteamUser(AbstractBaseUser, PermissionsMixin):
    USERNAME_FIELD = 'steamid'

    steamid = models.CharField(max_length=17, unique=True)
    personaname = models.CharField(max_length=255)
    profileurl = models.CharField(max_length=300)
    avatar = models.CharField(max_length=255)
    avatarmedium = models.CharField(max_length=255)
    avatarfull = models.CharField(max_length=255)

    # Add the other fields that can be retrieved from the Web-API if required

    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = SteamUserManager()

    def get_short_name(self):
        return self.personaname

    def get_full_name(self):
        return self.personaname

stats/forms.py
from django import forms

class 

stats/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import generic
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.views import View
import json, urllib, os


api_key = settings.SOCIAL_AUTH_STEAM_API_KEY


"""
view functions
"""
def login(request):
    context = {}
    return render(request,"login.html", context)

@login_required
def index(request):
    context = {}
    steam_id = request.user.steamid
    context["games"] = get_player_games(steam_id)
    context["recent_games"] = get_recent_games(steam_id)
    context["friends_list"] = get_friends_list(steam_id)
    # context["profile_info"] = get_player_profile(steam_id)
    return render(request, "home.html", context)

@login_required
def game_detail(request, appid):
    context = {}
    context["news_items"] = get_game_news(appid)
    context["game_name"] = get_game_name(appid)
    return render(request, "game_detail.html", context)


"""
steam_api methods
"""
def get_game_news(appid):
    urlobj = urllib.request.urlopen(
        f"http://api.steampowered.com/ISteamNews/GetNewsForApp/v0002/?key={api_key}&appid={appid}&count=5&maxlength=300&format=json"
    )
    data = json.loads(urlobj.read().decode("utf-8"))
    news_items = data["appnews"]["newsitems"]
    return news_items


def get_game_name(appid):
    game_urlobj = urllib.request.urlopen(
        f"http://api.steampowered.com/ISteamUserStats/GetSchemaForGame/v2/?key={api_key}&appid={appid}"
    )
    game_data = json.loads(game_urlobj.read().decode("utf-8"))
    if game_data["game"].get("gameName", False):
        game_name = game_data["game"]["gameName"]
        return game_name
    else:
        return ""


def get_player_games(steam_id):
    urlobj = urllib.request.urlopen(
        f"http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key={api_key}&steamid={steam_id}&format=json&include_appinfo=true"
    )
    data = json.loads(urlobj.read().decode("utf-8"))
    if data["response"].get("games", False):
        games = data["response"]["games"]
    else:
        games = []
    return games


def get_recent_games(steam_id):
    urlobj = urllib.request.urlopen(
        f"http://api.steampowered.com/IPlayerService/GetRecentlyPlayedGames/v0001/?key={api_key}&steamid={steam_id}&format=json"
    )
    data = json.loads(urlobj.read().decode("utf-8"))
    recent_games = data["response"]["games"]
    return recent_games


def get_friends_list(steam_id):
    urlobj = urllib.request.urlopen(
        f"http://api.steampowered.com/ISteamUser/GetFriendList/v0001/?key={api_key}&steamid={steam_id}&relationship=friend"
    )
    data = json.loads(urlobj.read().decode("utf-8"))
    friend_ids = ",".join(
        [friend["steamid"] for friend in data["friendslist"]["friends"]]
    )
    urlobj_2 = urllib.request.urlopen(
        f"http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key={api_key}&steamids={friend_ids}"
    )
    data_2 = json.loads(urlobj_2.read().decode("utf-8"))
    friends_list = data_2["response"]["players"]
    return friends_list


def get_player_profile(steam_id):
    urlobj = urllib.request.urlopen(
        f"http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key={api_key}&steamids={steam_id}"
    )
    data = json.loads(urlobj.read().decode("utf-8"))
    profile_info = data["response"]["players"][0]
    return profile_info

class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('stats:login')

stats/templates/common_head.html
{% load static %}
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Steam Stats!</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
  integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
  integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
  integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
  integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="https://use.fontawesome.com/805b1d4c7c.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.css">
<link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'base.css' %}" />

stats/templates/game_detail.html
{% extends "index.html" %}


{% block content %}

<head>
    {% if game_name %}
    <title>Steam Stats | {{game_name}}</title>
    {% endif %}
</head>
<div class="container">
    <div class="row">
        {% if game_name %}
        <h1>{{game_name}}</h1>
        {% endif %}
    </div>
    <div class="row">
        <ul class="nav nav-tabs" id="game-section-tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="news-tab" data-toggle="tab" href="#news" role="tab" aria-controls="news"
                    aria-selected="true">News</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="stats-tab" data-toggle="tab" href="#stats" role="tab" aria-controls="stats"
                    aria-selected="false">
                    Stats
                </a>
            </li>
        </ul>
    </div>
</div>


<div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="news" role="tabpanel" aria-labelledby="news-tab">
        <div class="container home-tabs">
            {% if news_items%}
            {% for news in news_items %}

            <div class='row'>
                <div>
                    <h3>{{ news.title }}</h3>
                </div>
                <div>{{ news.contents| safe}}</div>
                <div><a href="{{news.url}}">See Full article</a></div>
            </div>

            {% endfor %}
            {% else%}
            <div class="row">
                <p>No news for this game!</p>
            </div>
            {% endif %}
        </div>
    </div>
    <div class="tab-pane fade" id="stats" role="tabpanel" aria-labelledby="stats-tab">
        <div class="container home-tabs">
            <div class="chart-container">
                <canvas id="myChart" width="100" height="100"></canvas>
            </div>
        </div>
    </div>
</div>

<script>
    console.log("creating chart");
    var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
            datasets: [{
                label: 'Hours Played',
                data: [12, 19, 3, 5, 2, 3, 10],
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        },
        responsive: true,
        maintainAspectRatio: true,
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });
</script>
{% endblock %}

stats/templates/home.html
{% extends "index.html" %} {% load mathfilters %} {% block content %}
{{ recent_games|json_script:"recent-games" }}
<div class="jumbotron text-center home-banner">
  <div class="container">
    <div class="row">
      <div class="col">
        <h1 class="mx-auto">Welcome to Steam Stats!</h1>
      </div>
      <div class="col" style="border-style: solid; border-color: black; background-color: whitesmoke;">
        <div>{{request.user.personaname}}</div>
        <img src="{{request.user.avatarmedium}}" alt="No avatar available">
        <div><i class="fa fa-users" aria-hidden="true"></i> {{friends_list | length}} friends</div>
        <div><i class="fa fa-gamepad" aria-hidden="true"></i> {{ games | length}} games</div>
        <div>Member since: {{request.user.date_joined}}</div>
      </div>
    </div>

  </div>
</div>

<div class="container mx-auto">
  <div class="row">
    <ul class="nav nav-tabs" id="home-section-tabs" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="recentgames-tab" data-toggle="tab" href="#recentgames" role="tab"
          aria-controls="recentgames" aria-selected="false">
          Recently Played
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="allgames-tab" data-toggle="tab" href="#allgames" role="tab" aria-controls="allgames"
          aria-selected="true">All Games</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="friends-tab" data-toggle="tab" href="#friends" role="tab" aria-controls="friends"
          aria-selected="true">Friends</a>
      </li>
    </ul>
  </div>
  <div class="row  home-tabs">
    <div class="container tab-content" id="myTabContent">
      <div class="tab-pane fade" id="allgames" role="tabpanel" aria-labelledby="allgames-tab">
        <ul class="list-group list-group-flush home-tabs">
          {% if games %}
          {% for game in games %} {% if game.playtime_forever != 0 %}

          <li class="list-group-item home-tabs">
            <div class="row">
              <div class="col-sm">
                {{ game.name }}
                <div>
                  <img
                    src="http://media.steampowered.com/steamcommunity/public/images/apps/{{game.appid}}/{{game.img_logo_url}}.jpg"
                    alt="Game icon not available">
                </div>
              </div>
              <div class="col-sm">
                You've played this game for: {{game.playtime_forever}} minutes or
                {{ game.playtime_forever | div:60| truncatechars:6}} hours
              </div>
              <div class="col-sm">
                <a href="/game/{{game.appid}}" class="btn btn-dark btn-block">See Details</a>
              </div>
            </div>
          </li>
          {% endif %} {% endfor %}
          {% else %}
          <div> Could not fetch data from Steam Servers. Try again later.</div>
          {% endif %}
        </ul>
      </div>
      <div class="tab-pane fade show active" id="recentgames" role="tabpanel" aria-labelledby="recentgames-tab">
        <div class='row'>
          <div class="col col-sm">
            <ul class="list-group list-group-flush">
              {% for recent_game in recent_games %}
              <li class="list-group-item home-tabs">
                <div class="mb-2">{{ recent_game.name }}</div>
                <div>
                  <img
                    src="http://media.steampowered.com/steamcommunity/public/images/apps/{{recent_game.appid}}/{{recent_game.img_logo_url}}.jpg"
                    alt="Game icon not available">
                </div>
                <div class="mb-2">
                  Playtime Last two weeks: {{recent_game.playtime_2weeks}} minutes
                  or {{recent_game.playtime_2weeks | div:60| truncatechars:6}} hours
                </div>
                <div class="mb-2">
                  Total playtime: {{recent_game.playtime_forever}} minutes or
                  {{recent_game.playtime_forever | div:60| truncatechars:6}} hours
                </div>
              </li>
              {% endfor %}
            </ul>
          </div>
          <div class="col col-sm">
            <div class="chart-container">
              <canvas id="recentGameChart" width="100" height="100" style="padding-top: 10px;"></canvas>
            </div>
          </div>
        </div>
      </div>
      <div class="tab-pane fade" id="friends" role="tabpanel" aria-labelledby="friends-tab"
        style="padding-top: 10px; padding-bottom: 20px;">
        <div class="row">
          {% for friend in friends_list %}
          <div class="col">

            <div>{{friend.personaname}}</div>
            <div>
              <img src="{{friend.avatarfull}}" alt="No avatar available">
            </div>

          </div>
          {% endfor %}
        </div>

      </div>
    </div>

  </div>
</div>


<script>
  var recentGames = JSON.parse(document.getElementById('recent-games').textContent);
  var recentGameNames = recentGames.map(g => g.name);
  var recentGamePlayTimes = recentGames.map(g => g.playtime_2weeks / 60);
  var ctx = document.getElementById("recentGameChart").getContext("2d");
  var myChart = new Chart(ctx, {
    type: "doughnut",
    data: {
      labels: recentGameNames,
      datasets: [
        {
          label: "Hours Played",
          data: recentGamePlayTimes,
          // data: [1, 3],
          backgroundColor: [
            "#82a0d8",
            "#ca82d8",
            "rgba(255, 206, 86, 0.2)",
            "rgba(75, 192, 192, 0.2)",
            "rgba(153, 102, 255, 0.2)",
            "rgba(255, 159, 64, 0.2)",
          ],
          borderColor: [
            "#4c75bf",
            "#ac4cbf",
            "rgba(255, 206, 86, 1)",
            "rgba(75, 192, 192, 1)",
            "rgba(153, 102, 255, 1)",
            "rgba(255, 159, 64, 1)",
          ],
          borderWidth: 1,
        },
      ],
    },
    responsive: true,
    maintainAspectRatio: false,
    options: {
      scales: {
        // yAxes: [
        //   {
        //     ticks: {
        //       beginAtZero: true,
        //     },
        //   },
        // ],
      },
    },
  });
</script>
{% endblock %}

stats/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% include "common_head.html" %}
</head>

<body>
  <nav class="navbar navbar-custom navbar-expand-lg" id="nav-bar">
    <a class="navbar-brand" href="{% url "stats:index" %}">Steam Stats</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          {% if user.is_authenticated %}
          <a class="nav-link" href="{% url "stats:logout" %}">Logout</a>
          {% endif %}
        </li>
      </ul>

    </div>
  </nav>
  {% block content%} {% endblock %}
</body>

</html>

stats/templates/login.html
{% extends "index.html" %}
{% block content %}

<body>
    {% if user.is_authenticated %}
    <a href="{% url "stats:logout" %}">Logout</a>
    <br>
    Hello, {{ user.personaname }}
    {% else %}
    <a href="{% url "social:begin" "steam" %}">Sign in with Steam</a>
    {% endif %}
</body>

{% endblock %}